p
use v5.40;

# NAME
# ====
#
# Daje::Workflow::Config- Loads the JSON based configs and put them in a hash
#
# SYNOPSIS
# ========
#
#    use Daje::Workflow::Config;
#
#    # Single file
#    my $config = Daje::Workflow::Config->new(
#       path => "path",
#    )->load($filename);
#
#    my $value = $config->param($parameter);
#
# DESCRIPTION
# ===========
#
# Daje::Config is loading workflows from JSON files in a set folder
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.comE<gt>
#

our $VERSION = "0.01";

class Daje::Workflow::Config {
    use Mojo::Base -base;
    use Daje::Config;;

    field $path :parameter = "";
    field $config = {};

    method load($filename) {
        $config = Daje::Config->new(
            path => $path,
        )->load($filename);

    }

    method param($parameter) {
        return $config->{$parameter};
    }
}

1;
__END__


#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Workflow::Config- Loads the JSON based configs and put them in a hash



=head1 SYNOPSIS


   use Daje::Workflow::Config;

   # Single file
   my $config = Daje::Workflow::Config->new(
      path => "path",
   )->load($filename);

   my $value = $config->param($parameter);



=head1 DESCRIPTION


Daje::Config is loading workflows from JSON files in a set folder



=head1 REQUIRES

L<Daje::Workflow::Config> 

L<Daje::Config> 

L<Mojo::Base> 

L<v5.40> 


=head1 METHODS


=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.comE<gt>



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

